# Generated by Django 4.0.4 on 2022-05-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=70)),
                ('book_author', models.CharField(max_length=70)),
                ('year_of_publication', models.IntegerField(max_length=5)),
                ('publisher', models.CharField(max_length=70)),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
    ]
