# Generated by Django 4.0.4 on 2022-06-02 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='book_isbn',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
