# Generated by Django 4.0.4 on 2022-06-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
