# Generated by Django 4.0.4 on 2022-06-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_s',
            field=models.DateField(),
        ),
    ]
