# Generated by Django 4.0.4 on 2022-06-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_book_book_author_alter_book_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(max_length=255),
        ),
    ]
